'use strict';

const container = document.querySelector('#container');
const allInputs = document.querySelectorAll('.form-container input');
const email = document.getElementsByName('email')[0];
const password = document.getElementsByName('password')[0];
const confirmPassword = document.getElementsByName('confirm-password')[0];
const age = document.getElementsByName('age')[0];
const city = document.getElementsByName('city')[0];
const agreeCheckbox = document.getElementsByName('agree')[0];
const confirmButton = document.querySelector('[data-confirm-button]');
const clear = document.querySelector('[data-delete-button]');
const strengthText = document.getElementById('password-strength');
const showPass = document.querySelector('[data-toggle-password]');
const showConfirm = document.querySelector('[data-toggle-confirm]');

let form = {};
let validEmail = false;
let passwordStrength = 'слабкий';
let hasSpecialChar = false;
let validPassword = false;

const ul = document.createElement('ul');
ul.className = 'list';
showPass.addEventListener('click', () => {
    const img = showPass.querySelector('img');
    if (password.type === 'password') {
        password.type = 'text';
        img.src = 'styles/image/close.png';
    } else {
        password.type = 'password';
        img.src = 'styles/image/open.png';
    }
});

showConfirm.addEventListener('click', () => {
    const img = showConfirm.querySelector('img');
    if (confirmPassword.type === 'password') {
        confirmPassword.type = 'text';
        img.src = 'styles/image/close.png';
    } else {
        confirmPassword.type = 'password';
        img.src = 'styles/image/open.png';
    }
});

email.addEventListener('input', () => {
    const emailValidate = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (emailValidate.test(email.value) && email.value.trim().length >= 5) {
        validEmail = true;
        email.classList.remove('not-valid');
    } else {
        validEmail = false;
        email.classList.add('not-valid');
    }
});

password.addEventListener('input', () => {
    const trimmedPassword = password.value.trim();
    hasSpecialChar = /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/.test(trimmedPassword);
    //The symbols were generated by AI because I understood how to do regular expressions with numbers and letters, and I simply listed the symbols.

    if (trimmedPassword.length >= 8 && /[a-zA-Z]/.test(trimmedPassword) && /[0-9]/.test(trimmedPassword)) {
        validPassword = true;
        password.classList.remove('not-valid');

        if (trimmedPassword.length >= 10 && hasSpecialChar) {
            passwordStrength = 'сильний';
        } else if (trimmedPassword.length >= 10) {
            passwordStrength = 'нормальний';
        } else {
            passwordStrength = 'слабкий';
        }
    } else {
        validPassword = false;
        password.classList.add('not-valid');
        passwordStrength = 'слабкий';
    }
    if (password.value.trim().length > 0) {
        strengthText.textContent = `Сила пароля: ${passwordStrength === 'слабкий' ? 'слабкий' : passwordStrength === 'нормальний' ? 'середній' : 'сильний'}`;
        strengthText.className = `password-strength ${passwordStrength}`;
    } else {
        strengthText.textContent = '';
        strengthText.className = 'password-strength';
    }
});

confirmPassword.addEventListener('input', () => {
    if (confirmPassword.value === password.value && confirmPassword.value.length > 0) {
        confirmPassword.classList.remove('not-valid');
    } else if (confirmPassword.value.length > 0) {
        confirmPassword.classList.add('not-valid');
    }
});

age.addEventListener('input', () => {
    if (age.value >= 16 && age.value <= 120) {
        age.classList.remove('not-valid');
    } else {
        age.classList.add('not-valid');
    }
});

city.addEventListener('input', () => {
    if (city.value) {
        city.classList.remove('not-valid');
    } else {
        city.classList.add('not-valid');
    }
});

agreeCheckbox.addEventListener('change', () => {
    if (agreeCheckbox.checked) {
        agreeCheckbox.classList.remove('not-valid');
    } else {
        agreeCheckbox.classList.add('not-valid');
    }
});

confirmButton.addEventListener('click', e => {
    e.preventDefault();

    console.log('validPassword:', validPassword, 'password value:', password.value);

    if (!validEmail) {
        email.focus();
        email.classList.add('not-valid');
        return;
    }
    if (!validPassword) {
        password.focus();
        password.classList.add('not-valid');
        return;
    }
    if (password.value !== confirmPassword.value || confirmPassword.value.length === 0) {
        confirmPassword.focus();
        confirmPassword.classList.add('not-valid');
        return;
    }
    if (age.value < 16 || age.value > 120 || !age.value) {
        age.focus();
        age.classList.add('not-valid');
        return;
    }
    if (!city.value) {
        city.focus();
        city.classList.add('not-valid');
        return;
    }
    if (!agreeCheckbox.checked) {
        agreeCheckbox.focus();
        agreeCheckbox.classList.add('not-valid');
        return;
    }

    form['email'] = email.value;
    form['age'] = age.value;
    form['city'] = city.value;
    ul.innerHTML = '';
    for (let key in form) {
        let li = document.createElement('li');
        li.textContent = `${key}: ${form[key]}`;
        ul.appendChild(li);
    }
});

clear.addEventListener('click', e => {
    e.preventDefault();
    hasSpecialChar = false;
    validPassword = false;
    validEmail = false;
    passwordStrength = 'weak';
    ul.innerHTML = '';
    form = {};
    strengthText.textContent = '';
    strengthText.className = 'password-strength';

    password.type = 'password';
    confirmPassword.type = 'password';
    showPass.querySelector('img').src = 'styles/image/open.png';
    showConfirm.querySelector('img').src = 'styles/image/open.png';

    for (let input of allInputs) {
        if (input.type === 'checkbox') {
            input.checked = false;
        } else {
            input.value = '';
        }
        input.classList.remove('not-valid');
    }
});

container.appendChild(ul);